puts "🌱 Seeding spices..."

# Seed your database here
Record.create(artist: "Bill Evans Trio", album: "Portrait In Jazz", year: 1959, image_url: "https://i.discogs.com/mA5Z-COqYtSJ2CkbxL1FlclKyIZVOKYioy1YeKplO-Q/rs:fit/g:sm/q:90/h:600/w:588/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEzMjQy/NTQtMTQ3MTQ3NDc2/Ni0zNDkzLmpwZWc.jpeg")
Record.create(artist: "Grant Green", album: "Street of Dreams" , year: 1964 , image_url: "https://i.discogs.com/c0xcotAsi93rXwRlhCSkng1IhbCFjfupEVqeQJzcDPo/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE4Njc5/NTctMTM1MTcyMDI4/NS02NjQ5LmpwZWc.jpeg" )
Record.create(artist: "The Art Farmer Quartet" , album: "To Sweeden With Love", year: 1964 , image_url: "https://i.discogs.com/lcL1BJZDYs84MD4M9-vczPsdilszjPcE7j4v5nOBvx8/rs:fit/g:sm/q:90/h:500/w:499/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIyOTc4/NjEtMTI3NTIzMTI4/OS5qcGVn.jpeg" )
Record.create(artist: "Wes Montgomery", album: "Full House live in Berkeley", year: "1964", image_url: "https://i.discogs.com/dd_tA55kag2BHvykUOhUHMDprZU3QyriTkT6XOtdmCc/rs:fit/g:sm/q:90/h:596/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIxNTg5/NjgtMTU4NjAwMzE3/Ni03NDU4LmpwZWc.jpeg")
Record.create(artist: "Duke Ellington & John Coltrane" , album: "Duke Ellington & John Coltrane", year: 1962, image_url: "https://i.discogs.com/WUjs291Km4ccDPdPNaixBLERO4MXrHCXV2wZ2K72PQM/rs:fit/g:sm/q:90/h:600/w:592/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE0MDY0/MjktMTM0NjI1ODMw/NC02ODQ4LmpwZWc.jpeg" )
Record.create(artist: "The Magnetic Fields", album: "The Charm Of The Highway Strip", year: 1994, image_url: "https://i.discogs.com/eqnn0GXe9PvHWKcTHrkogJDIrzctXT-RCrMFzGhIWXU/rs:fit/g:sm/q:90/h:593/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEyNjEw/MzItMTIwNDU2Njk3/NS5qcGVn.jpeg" )
Record.create(artist: "Robert Fripp/Brian Eno", album: "Air Structures", year: 1978, image_url: "https://i.discogs.com/0WQ2we5a7VQxdpN4298Td_ZmnaeBR76960ofKfbz6QY/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE2MDUz/NzUtMTY1ODIyODUy/NS03MzY2LmpwZWc.jpeg" )
Record.create(artist: "Talking Heads", album: "Remain In Light", year: 1980, image_url: "https://i.discogs.com/jdBOSwi9DZ2IQaGt62kWJI-e6IlhxNYCnTkDiGR835M/rs:fit/g:sm/q:90/h:550/w:550/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExNzQx/MDMtMTM5MzA3ODM4/NC03MTY3LmpwZWc.jpeg" )
Record.create(artist: "William Onyeabor", album: "Who Is William Onyeabor?", year: 1978, image_url: "https://i.discogs.com/_sM-3UMIGbM-9JbSBj3RlX0PaFbE_39iMkzipU6rsbc/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ5OTc2/NzMtMTM5NjcyNzA4/OS0zODE1LmpwZWc.jpeg" )
Record.create(artist: "Joy Division", album: "Unknown Pleasures", year: 1979, image_url: "https://i.discogs.com/nigdVdUz5433GIo5-wLxHaJHL0bASlDWJtUB09m7Wjc/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExNDAw/LTE0ODIyMjk4MTIt/NDk5MC5qcGVn.jpeg" )
Record.create(artist: "Mac DeMarco", album: "Another One", year: 2015, image_url: "https://i.discogs.com/xHZiLBtbLw6DTreBM_PHMlSaUXKkSspDUiMwgOYR1es/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTczMTU3/NDUtMTQzODcwNzE0/NS01MTczLmpwZWc.jpeg")
Record.create(artist: "Cobra Man", album: "New Driveway Soundtrack", year: 2017, image_url: "https://f4.bcbits.com/img/a3030478123_10.jpg" )
Record.create(artist: "Brian Eno", album: "Another Green World", year: 1975, image_url: "https://i.discogs.com/eVKq_sLFNwSqhypWdaKhd6oss7pE1oRn3zPDYvUHz9g/rs:fit/g:sm/q:90/h:600/w:599/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExNjUy/NS0xNTM4MzAwMzk2/LTg4OTkuanBlZw.jpeg" )
Record.create(artist: "The Mars Volta", album: "De-Loused In The Comatorium", year: 2003, image_url: "https://i.discogs.com/A8fuO76ZXZaM7Qo2Tl38blLgvsWAkOtEcrTwf0Mtpb8/rs:fit/g:sm/q:90/h:598/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTY0MTYx/MC0xNTEwODUyMzUz/LTQzMjMuanBlZw.jpeg" )
Record.create(artist: "LCD Soundsystem", album: "London Sessions", year: 2011, image_url: "https://i.discogs.com/MkoKyoWURfUWnCGxqXcPA4auSAUJfVMX2GQwqcg0Els/rs:fit/g:sm/q:90/h:598/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI3MTQy/MzctMTI5NzcyODE1/My5qcGVn.jpeg")
Record.create(artist: "Bill Evans Trio", album: "Sunday At The Village Vangaurd", year: 1959, image_url: "https://i.discogs.com/qzdI9vmF430nMwr3Ii2GrtYq800RzJgW9LJXD6LeSXY/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEyNzY2/NTM5LTE1NDE1MzQ0/NTMtMzQ0MS5qcGVn.jpeg" )
Record.create(artist: "Alex Cameron", album: "Forced Witness", year: 2017, image_url: "https://i.discogs.com/4pP_bADvHf-tcHuOFwkaqi9y3b4WMKUDQt51BeZON3Q/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwODA4/ODM1LTE1MDQ2NTU0/MTItOTE0Ny5qcGVn.jpeg")
Record.create(artist: "Todd Terje", album: "It's Album Time", year: 2014, image_url: "https://i.discogs.com/hwa11nzuJz9ZzDyTDjQ27ywKmqXQNVQb_KrZQqjIUoQ/rs:fit/g:sm/q:90/h:536/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTU1MTM1/MjAtMTU4MjIwNTA3/MC02Nzc1LmpwZWc.jpeg" )
Record.create(artist: "Animal Collective", album: "Merriweather Post Pavilion", year: 2009, image_url: "https://i.discogs.com/7PO58jL3ee8ev8st01DxesiJ41FeFkDXyZyR0R3ghdE/rs:fit/g:sm/q:90/h:450/w:450/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1OTIx/MTgtMTIzMDc5OTk5/Ny5qcGVn.jpeg" )
Record.create(artist: "The War On Drugs", album: "Slave Ambient", year: 2011, image_url: "https://i.discogs.com/Oh3HaSFqwYybo79g_b3lgtqM4_aAuXtlLEQLIjPOkis/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwODQ5/ODIxLTE1MDUzMjUz/OTItODc4MS5qcGVn.jpeg" )
Record.create(artist: "Brian Eno", album: "Here Come The Warm Jets" , year: 1973, image_url: "https://i.discogs.com/33F2tzTS1FFgXvaniwjdCbQv4-z2b3PFK-f_soIyQ8U/rs:fit/g:sm/q:90/h:583/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ0MDE0/NDEtMTM4NTY0MDMz/MC00OTg2LmpwZWc.jpeg" )
Record.create(artist: "Holy Ghost!", album: "Holy Ghost!", year: 2011, image_url: "https://i.discogs.com/dliTjLQbGGCDhQIimDE250uEN2TVHtJoHL7FV-BnTAg/rs:fit/g:sm/q:90/h:600/w:598/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI3OTYz/OTktMTU4Njc5NzU0/Mi00NTk1LmpwZWc.jpeg" )
Record.create(artist: "Hot Chip", album: "In Our Heads", year: 2012, image_url: "https://i.discogs.com/D_ULLNepniop3WVq8KrixydHzcIsJyvaywhrgBXJswU/rs:fit/g:sm/q:90/h:529/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM2NzEz/OTAtMTMzOTczMTc5/My0yNzY0LmpwZWc.jpeg")
Record.create(artist: "David Bowie", album: "Low", year: 1977, image_url: "https://i.discogs.com/U3pqMqj3_qkfW3A7TSy0MJCOfaPuERLdNEWjjxgFjRs/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIxNjE2/Ni0xMjc1NjI1NjQ5/LmpwZWc.jpeg")
Record.create(artist: "The Unicorns", album: "Who Will Cut Our Hair When We're Gone", year: 2014, image_url: "https://i.discogs.com/l44Klcnx4LDff5Nyrqi9suR54Tl7t1muIOOswSgY43Q/rs:fit/g:sm/q:90/h:596/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTU5NTEz/OTYtMTQwNzE5MDU4/OC05NzQ3LmpwZWc.jpeg")




puts "✅ Done seeding!"
